# Site settings
title: an AI course progress record
description: "Records on CoTAI course, mathematic foundations course for AI future researcher"
url: "https://hikari122.github.io/CoTAI_course/"
author:
  name: "Quang Nguyen"
  email: "nnquang122@gmail.com"
  url: ""

# Build settings
baseurl: /CoTAI_course/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: ""

# Options
custom_header: false
custom_nav_footer: false
reverse: false
